"""add address and coordinates to sites and suppliers

Revision ID: 0d648b210f35
Revises: 4f190a48e6a2
Create Date: 2026-08-17 08:58:11.212020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d648b210f35'
down_revision: Union[str, Sequence[str], None] = '4f190a48e6a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('sites', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('sites', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('suppliers', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('suppliers', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('suppliers', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'longitude')
    op.drop_column('suppliers', 'latitude')
    op.drop_column('suppliers', 'address')
    op.drop_column('sites', 'longitude')
    op.drop_column('sites', 'latitude')
    op.drop_column('sites', 'address')
    # ### end Alembic commands ###
