"""add scope to lca_calculations

Revision ID: 4f190a48e6a2
Revises: df6e8b70e7e0
Create Date: 2026-08-16 21:23:43.000316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f190a48e6a2'
down_revision: Union[str, Sequence[str], None] = 'df6e8b70e7e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lca_calculations', sa.Column('scope', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lca_calculations', 'scope')
    # ### end Alembic commands ###
