"""add tax_id to companies

Revision ID: d5875ccc4962
Revises: 9ea61845a9c8
Create Date: 2026-07-24 10:01:01.895734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5875ccc4962'
down_revision: Union[str, Sequence[str], None] = '9ea61845a9c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('tax_id', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_companies_tax_id'), 'companies', ['tax_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_tax_id'), table_name='companies')
    op.drop_column('companies', 'tax_id')
    # ### end Alembic commands ###
