"""add site_id and distance_km to suppliers

Revision ID: df6e8b70e7e0
Revises: ea831a4c3b26
Create Date: 2026-08-12 02:51:25.242869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6e8b70e7e0'
down_revision: Union[str, Sequence[str], None] = 'ea831a4c3b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('site_id', sa.Integer(), nullable=True))
    op.add_column('suppliers', sa.Column('distance_km', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'suppliers', 'sites', ['site_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'distance_km')
    op.drop_column('suppliers', 'site_id')
    # ### end Alembic commands ###
