"""add lca_calculations table

Revision ID: ea831a4c3b26
Revises: 258be94a76ca
Create Date: 2026-08-06 22:55:52.420824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea831a4c3b26'
down_revision: Union[str, Sequence[str], None] = '258be94a76ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lca_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('import_log_id', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('process_ref', sa.String(length=255), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('impact_method', sa.String(length=255), nullable=True),
    sa.Column('total_carbon_footprint', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('result_breakdown', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['import_log_id'], ['import_logs.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lca_calculations_id'), 'lca_calculations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lca_calculations_id'), table_name='lca_calculations')
    op.drop_table('lca_calculations')
    # ### end Alembic commands ###
